features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: false
  favicon: true
logo:
  use_default: false
  path: 'public://ADM logo.png'
favicon:
  use_default: false
  path: 'public://ADM logo_0.png'
  mimetype: image/png
