palette:
  top: '#00adee'
  bottom: '#00adee'
  bg: '#ffffff'
  sidebar: '#ffffff'
  sidebarborders: '#d0d0d0'
  footer: '#000066'
  titleslogan: '#ffffff'
  text: '#3b3b3b'
  link: '#0073b6'
logo: 'public://color/bartik-70fe992a/logo.svg'
stylesheets:
  - 'public://color/bartik-70fe992a/colors.css'
files:
  - 'public://color/bartik-70fe992a/logo.svg'
  - 'public://color/bartik-70fe992a/colors.css'
